-- QUIZ PLATFORM — ESTADÍSTICAS FASE 2
-- Ejecutar una vez en Supabase SQL Editor.
-- No guarda nombres, correos, teléfonos ni otros datos personales.

create table if not exists public.quiz_attempts (
  attempt_id text primary key,
  schema_version integer not null default 1,
  completed_at timestamptz not null,
  duration_seconds integer,
  route text not null,
  client_id text not null,
  client_slug text not null,
  client_name text,
  period_year integer,
  period_month text not null,
  quiz_id text not null,
  quiz_slug text not null,
  quiz_title text,
  correct integer not null,
  wrong integer not null,
  total integer not null,
  percent integer not null,
  created_at timestamptz not null default now()
);

create table if not exists public.quiz_answers (
  id bigint generated by default as identity primary key,
  attempt_id text not null references public.quiz_attempts(attempt_id) on delete cascade,
  question_id text,
  question_text text not null,
  selected_answer text,
  correct_answer text,
  is_correct boolean not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_quiz_attempts_client_period
  on public.quiz_attempts (client_slug, period_year, period_month);
create index if not exists idx_quiz_attempts_quiz
  on public.quiz_attempts (client_slug, quiz_slug);
create index if not exists idx_quiz_attempts_completed_at
  on public.quiz_attempts (completed_at);
create index if not exists idx_quiz_answers_attempt
  on public.quiz_answers (attempt_id);
create index if not exists idx_quiz_answers_question
  on public.quiz_answers (question_id);

alter table public.quiz_attempts enable row level security;
alter table public.quiz_answers enable row level security;

-- No public SELECT/INSERT policies are created intentionally.
-- The Vercel serverless endpoint writes through the Supabase service role.

create or replace function public.record_quiz_attempt(p_event jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  inserted boolean := false;
  answer jsonb;
begin
  insert into public.quiz_attempts (
    attempt_id, schema_version, completed_at, duration_seconds, route,
    client_id, client_slug, client_name,
    period_year, period_month,
    quiz_id, quiz_slug, quiz_title,
    correct, wrong, total, percent
  ) values (
    p_event->>'attemptId',
    coalesce((p_event->>'schemaVersion')::integer, 1),
    (p_event->>'completedAt')::timestamptz,
    nullif(p_event->>'durationSeconds', '')::integer,
    p_event->>'route',
    p_event->'client'->>'id',
    p_event->'client'->>'slug',
    p_event->'client'->>'name',
    nullif(p_event->'period'->>'year', '')::integer,
    p_event->'period'->>'month',
    p_event->'quiz'->>'id',
    p_event->'quiz'->>'slug',
    p_event->'quiz'->>'title',
    (p_event->'score'->>'correct')::integer,
    (p_event->'score'->>'wrong')::integer,
    (p_event->'score'->>'total')::integer,
    (p_event->'score'->>'percent')::integer
  ) on conflict (attempt_id) do nothing;

  get diagnostics inserted = row_count;

  if inserted then
    for answer in select * from jsonb_array_elements(coalesce(p_event->'answers', '[]'::jsonb)) loop
      insert into public.quiz_answers (
        attempt_id, question_id, question_text, selected_answer, correct_answer, is_correct
      ) values (
        p_event->>'attemptId',
        answer->>'questionId',
        coalesce(answer->>'question', ''),
        answer->>'selected',
        answer->>'correct',
        coalesce((answer->>'isCorrect')::boolean, false)
      );
    end loop;
  end if;

  return jsonb_build_object('inserted', inserted > 0, 'attemptId', p_event->>'attemptId');
end;
$$;

revoke all on function public.record_quiz_attempt(jsonb) from public;
